name = "anastasia-labs/utxo-indexers-exercises"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Possible solutions to given exercises in the UTxO indexers design pattern"

[repository]
user = "anastasia-labs"
project = "utxo-indexers-exercises"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
